# Generated by Django 6.0.8 on 2026-09-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_rental_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
