# Generated by Django 6.0.8 on 2026-09-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_rentalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('active', 'Active'), ('returned', 'Returned')], default='active', max_length=20),
        ),
    ]
